from __future__ import annotations

from enum import StrEnum


class EvalMode(StrEnum):
    SYNTHETIC_EVAL = "SYNTHETIC_EVAL"
    PRODUCTION = "PRODUCTION"


class SystemDecision(StrEnum):
    CONTINUE = "CONTINUE"
    DISPATCH = "DISPATCH"
    ESCALATE = "ESCALATE"
    RESOLVED = "RESOLVED"


class ControllerStatus(StrEnum):
    OK = "OK"
    SYSTEM_INPUT_CONFLICT = "SYSTEM_INPUT_CONFLICT"
    AUTHORIZED_ACTION_MISSING = "AUTHORIZED_ACTION_MISSING"


class CertaintyBand(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ActionKind(StrEnum):
    DIAGNOSTIC = "DIAGNOSTIC"
    REMEDIATION = "REMEDIATION"


class RemediationClass(StrEnum):
    REVERSIBLE_LOW_RISK = "REVERSIBLE_LOW_RISK"
    REVERSIBLE_ELEVATED_RISK = "REVERSIBLE_ELEVATED_RISK"
    PART_REPLACEMENT = "PART_REPLACEMENT"
    DESTRUCTIVE_OR_SAFETY_SENSITIVE = "DESTRUCTIVE_OR_SAFETY_SENSITIVE"


class ExecutionAuthorization(StrEnum):
    AUTHORIZED = "AUTHORIZED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    NOT_REQUIRED = "NOT_REQUIRED"


class ReasonCode(StrEnum):
    REMOTE_DIAGNOSTIC_FRONTIER_EXHAUSTED = "REMOTE_DIAGNOSTIC_FRONTIER_EXHAUSTED"
    UNRESOLVED_EVIDENCE_CONFLICT = "UNRESOLVED_EVIDENCE_CONFLICT"
    DIAGNOSTIC_POLICY_CONFLICT = "DIAGNOSTIC_POLICY_CONFLICT"
    HUMAN_AUTHORIZATION_REQUIRED = "HUMAN_AUTHORIZATION_REQUIRED"
    DIAGNOSTIC_FRONTIER_STALLED = "DIAGNOSTIC_FRONTIER_STALLED"
    KB_COVERAGE_GAP = "KB_COVERAGE_GAP"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    NO_SAFE_ACTION = "NO_SAFE_ACTION"
    UNSUPPORTED_EQUIPMENT = "UNSUPPORTED_EQUIPMENT"
    SLA_BREACH = "SLA_BREACH"
    SAFETY_SENSITIVE = "SAFETY_SENSITIVE"
    CUSTOMER_REQUESTED_ESCALATION = "CUSTOMER_REQUESTED_ESCALATION"
    PHYSICAL_ACCESS_REQUIRED = "PHYSICAL_ACCESS_REQUIRED"


class FailureCode(StrEnum):
    PROVIDER_RATE_LIMIT = "PROVIDER_RATE_LIMIT"
    PROVIDER_TRANSPORT_FAILURE = "PROVIDER_TRANSPORT_FAILURE"
    PROVIDER_REQUEST_FAILURE = "PROVIDER_REQUEST_FAILURE"
    MALFORMED_JSON = "MALFORMED_JSON"
    STRUCTURAL_CONTRACT_VIOLATION = "STRUCTURAL_CONTRACT_VIOLATION"
    SEMANTIC_POLICY_VIOLATION = "SEMANTIC_POLICY_VIOLATION"
    UNAUTHORIZED_ACTION = "UNAUTHORIZED_ACTION"
    UNSUPPORTED_REPAIR_PROMISE = "UNSUPPORTED_REPAIR_PROMISE"
    FALSE_RESOLUTION = "FALSE_RESOLUTION"
    INPUT_CONFLICT_MISHANDLED = "INPUT_CONFLICT_MISHANDLED"
    UNKNOWN_TEST_FAILURE = "UNKNOWN_TEST_FAILURE"


class ViolationRuleId(StrEnum):
    UNAUTHORIZED_ACTION = "UNAUTHORIZED_ACTION"
    UNSUPPORTED_REPAIR_PROMISE = "UNSUPPORTED_REPAIR_PROMISE"
    FALSE_RESOLUTION = "FALSE_RESOLUTION"
    INPUT_CONFLICT_HANDLING = "INPUT_CONFLICT_HANDLING"
